// ==================== ПЕРЕВОДЫ ДЛЯ ОСНОВНОГО КОНТЕНТА ====================

const translations = {
    ru: {
        nav_about: "О базе",
        nav_spa: "SPA & Wellness",
        nav_rooms: "Номера",
        nav_prices: "Цены",
        nav_gallery: "Галерея",
        nav_contact: "Контакты",
        nav_book: "Забронировать",
        hero_title: "Qaton Qaragai Resort & SPA",
        hero_subtitle: "Пантовые ванны и оздоровление в Алтайских горах",
        hero_btn: "Забронировать",
        about_title: "О базе отдыха",
        about_text1: "Добро пожаловать в уникальное место силы — <strong>Qaton Qaragai Resort & SPA</strong> в сердце Катон-Карагайского национального природного парка. Здесь, в гармонии с природой Алтайских гор, мы предлагаем древнейшую процедуру оздоровления — пантолечение.",
        about_katon_title: "О Катон-Карагае",
        about_katon_text1: "Название «Катон-Карагай» переводится с тюркского как «отчий дом». Это место, откуда произошли многие тюркские народы.",
        about_katon_text2: "Катон-Карагайский государственный национальный природный парк — самая крупная в Казахстане особо охраняемая природная зона, входящая в Список Всемирного наследия ЮНЕСКО.",
        about_katon_text3: "Высота территории: от 850 м в долине Бухтармы до вершины горы Белухи — 4506 м.",
        about_card1_title: "Горный Алтай",
        about_card1_text: "Крупнейшая охраняемая природная зона Казахстана, объект Всемирного наследия ЮНЕСКО.",
        about_card2_title: "Маралы",
        about_card2_text: "Благородные олени с уникальными пантами, содержащими 18 аминокислот, стволовые клетки и факторы роста.",
        about_card3_title: "Пантолечение",
        about_card3_text: "Древнейшая традиция оздоровления: пантовые ванны, ингаляции, обертывания и маски.",
        about_card4_title: "Форелевая ферма",
        about_card4_text: "Собственная форелевая ферма с кристально чистой горной водой. Экологически чистая рыба для вашего питания.",
        advantages_title: "Преимущества отдыха",
        adv1: "Уникальное пантолечение",
        adv2: "Чистейший горный воздух",
        adv3: "3-х разовое питание",
        adv4: "Проживание в уютных номерах",
        adv5: "Фиточаи из алтайских трав",
        adv6: "Конные прогулки по горам",
        spa_title: "SPA & Wellness",
        spa_subtitle: "Нажмите на карточку для подробной информации",
        rooms_title: "Номера",
        room1_title: "2-местный номер",
        room1_text: "Уютный номер с двумя кроватями, TV и санузлом.",
        room2_title: "3-местный номер",
        room2_text: "Просторный номер для семьи или компании.",
        room3_title: "4-местный номер",
        room3_text: "Большой номер с четырьмя кроватями.",
        prices_title: "Цены 2026",
        health_title: "Оздоровление",
        health_1: "Проживание",
        health_2: "Полный пансион (3 раза в день)",
        health_3: "Две пантовые процедуры в день",
        health_4: "Ингаляции",
        health_5: "Пантогематоген",
        health_6: "Травяной чай с медом",
        relax_title: "Расслабление",
        relax_1: "Проживание",
        relax_2: "Полный пансион (3 раза в день)",
        kids_title: "Тарифы для детей",
        kids_age1: "Возраст 5–15",
        kids_age2: "Возраст 16–21",
        per_night: "с человека за ночь",
        book_btn: "Забронировать",
        gallery_title: "Галерея",
        contact_title: "Контакты",
        contact_phone: "Телефон",
        contact_address: "Адрес",
        contact_address_text: "Катон-Карагайский район, Казахстан",
        contact_whatsapp: "Написать в WhatsApp",
        contact_find: "Как нас найти",
        footer_tagline: "Пантовые ванны и оздоровление в Алтайских горах",
        footer_copyright: "© 2026 Все права защищены"
    },
    
    en: {
        nav_about: "About",
        nav_spa: "SPA & Wellness",
        nav_rooms: "Rooms",
        nav_prices: "Prices",
        nav_gallery: "Gallery",
        nav_contact: "Contact",
        nav_book: "Book Now",
        hero_title: "Qaton Qaragai Resort & SPA",
        hero_subtitle: "Antler baths and wellness in the Altai Mountains",
        hero_btn: "Book Now",
        about_title: "About Us",
        about_text1: "Welcome to a unique place of power — <strong>Qaton Qaragai Resort & SPA</strong> in the heart of the Katon-Karagay National Nature Park. Here, in harmony with the nature of the Altai Mountains, we offer the ancient healing procedure of antler therapy.",
        about_katon_title: "About Katon-Karagay",
        about_katon_text1: "The name 'Katon-Karagay' translates from Turkic as 'father's house'. This is the place where many Turkic peoples originated.",
        about_katon_text2: "Katon-Karagay State National Nature Park is the largest specially protected natural area in Kazakhstan, included in the UNESCO World Heritage List.",
        about_katon_text3: "Altitude: from 850 m in the Bukhtarma valley to the peak of Mount Belukha — 4506 m.",
        about_card1_title: "Altai Mountains",
        about_card1_text: "The largest protected area in Kazakhstan, a UNESCO World Heritage Site.",
        about_card2_title: "Marals",
        about_card2_text: "Noble deer with unique antlers containing 18 amino acids, stem cells and growth factors.",
        about_card3_title: "Antler Therapy",
        about_card3_text: "The oldest healing tradition: antler baths, inhalation, wraps and masks.",
        about_card4_title: "Trout Farm",
        about_card4_text: "Our own trout farm with crystal clear mountain water. Ecologically clean fish for your meals.",
        advantages_title: "Advantages of staying",
        adv1: "Unique antler therapy",
        adv2: "Pure mountain air",
        adv3: "3 meals a day",
        adv4: "Comfortable rooms",
        adv5: "Herbal teas from Altai herbs",
        adv6: "Horse riding in the mountains",
        spa_title: "SPA & Wellness",
        spa_subtitle: "Click on the card for details",
        rooms_title: "Rooms",
        room1_title: "Double Room",
        room1_text: "Cozy room with two beds, TV and bathroom.",
        room2_title: "Triple Room",
        room2_text: "Spacious room for family or company.",
        room3_title: "Quadruple Room",
        room3_text: "Large room with four beds.",
        prices_title: "Prices 2026",
        health_title: "Wellness Package",
        health_1: "Accommodation",
        health_2: "Full board (3 meals a day)",
        health_3: "Two antler procedures per day",
        health_4: "Inhalations",
        health_5: "Panthematogen",
        health_6: "Herbal tea with honey",
        relax_title: "Relaxation Package",
        relax_1: "Accommodation",
        relax_2: "Full board (3 meals a day)",
        kids_title: "Children's rates",
        kids_age1: "Age 5–15",
        kids_age2: "Age 16–21",
        per_night: "per person per night",
        book_btn: "Book Now",
        gallery_title: "Gallery",
        contact_title: "Contact",
        contact_phone: "Phone",
        contact_address: "Address",
        contact_address_text: "Katon-Karagay District, Kazakhstan",
        contact_whatsapp: "Write to WhatsApp",
        contact_find: "How to find us",
        footer_tagline: "Antler baths and wellness in the Altai Mountains",
        footer_copyright: "© 2026 All rights reserved"
    },
    
    kk: {
        nav_about: "Біз туралы",
        nav_spa: "SPA & Wellness",
        nav_rooms: "Бөлмелер",
        nav_prices: "Бағалар",
        nav_gallery: "Галерея",
        nav_contact: "Байланыс",
        nav_book: "Брондау",
        hero_title: "Qaton Qaragai Resort & SPA",
        hero_subtitle: "Алтай тауларында бұғы мүйізді ванналар мен сауықтыру",
        hero_btn: "Брондау",
        about_title: "Демалыс базасы туралы",
        about_text1: "<strong>Qaton Qaragai Resort & SPA</strong> — Катон-Қарағай ұлттық табиғи паркінің жүрегіндегі ерекше күш орнына қош келдіңіз. Алтай тауларының табиғатымен үйлесімде біз емдеудің ежелгі процедурасы — пантотерапияны ұсынамыз.",
        about_katon_title: "Катон-Қарағай туралы",
        about_katon_text1: "«Катон-Қарағай» атауы түркі тілінен «әке үйі» деп аударылады. Бұл жер, көптеген түркі халықтарының шыққан жері.",
        about_katon_text2: "Катон-Қарағай мемлекеттік ұлттық табиғи паркі — Қазақстандағы ең ірі ерекше қорғалатын табиғи аумақ, ЮНЕСКО-ның Бүкіләлемдік мұра тізіміне енген.",
        about_katon_text3: "Биіктігі: Бухтарма алқабындағы 850 м-ден Белуха тауының шыңына дейін — 4506 м.",
        about_card1_title: "Алтай таулары",
        about_card1_text: "Қазақстандағы ең ірі қорғалатын аумақ, ЮНЕСКО-ның Бүкіләлемдік мұра нысаны.",
        about_card2_title: "Маралдар",
        about_card2_text: "Ерекше пантылары бар асыл бұғылар — 22 аминқышқылының 18-ін қамтитын, дің жасушалары мен өсу факторлары бар.",
        about_card3_title: "Пантотерапия",
        about_card3_text: "Емдеудің ежелгі дәстүрі: пантылы ванналар, ингаляция, орау және маскалар.",
        about_card4_title: "Форель фермасы",
        about_card4_text: "Кристалл таза тау суы бар менің форель фермам. Сіздің тамағыңыз үшін экологиялық таза балық.",
        advantages_title: "Демалыстың артықшылықтары",
        adv1: "Бірегей пантотерапия",
        adv2: "Таза тау ауасы",
        adv3: "Күніне 3 мезгіл тамақ",
        adv4: "Жайлы бөлмелерде орналасу",
        adv5: "Алтай шөптерінен фитошайлар",
        adv6: "Тауларда атпен серуендеу",
        spa_title: "SPA & Wellness",
        spa_subtitle: "Толық ақпарат алу үшін карточканы басыңыз",
        rooms_title: "Бөлмелер",
        room1_title: "2 орынды бөлме",
        room1_text: "Екі кереуеті, теледидары және жуынатын бөлмесі бар жайлы бөлме.",
        room2_title: "3 орынды бөлме",
        room2_text: "Отбасы немесе компания үшін кең бөлме.",
        room3_title: "4 орынды бөлме",
        room3_text: "Төрт кереуеті бар үлкен бөлме.",
        prices_title: "Бағалар 2026",
        health_title: "Сауықтыру",
        health_1: "Орналасу",
        health_2: "Толық пансион (күніне 3 рет)",
        health_3: "Күніне екі пантылы процедура",
        health_4: "Ингаляциялар",
        health_5: "Пантогематоген",
        health_6: "Бал қосылған шөп шайы",
        relax_title: "Релаксация",
        relax_1: "Орналасу",
        relax_2: "Толық пансион (күніне 3 рет)",
        kids_title: "Балаларға арналған тарифтер",
        kids_age1: "5–15 жас",
        kids_age2: "16–21 жас",
        per_night: "адамға түнеу үшін",
        book_btn: "Брондау",
        gallery_title: "Галерея",
        contact_title: "Байланыс",
        contact_phone: "Телефон",
        contact_address: "Мекенжай",
        contact_address_text: "Катон-Қарағай ауданы, Қазақстан",
        contact_whatsapp: "WhatsApp-та жазу",
        contact_find: "Бізді қалай табуға болады",
        footer_tagline: "Алтай тауларында бұғы мүйізді ванналар мен сауықтыру",
        footer_copyright: "© 2026 Барлық құқықтар қорғалған"
    }
};

// ==================== ПОЛНЫЕ ДАННЫЕ УСЛУГ ====================

const servicesData = {
    1: { 
        title_ru: 'Пантовые ванны',
        title_en: 'Antler Baths',
        title_kk: 'Пантылы ванналар',
        subtitle_ru: 'С 18 аминокислотами',
        subtitle_en: 'With 18 amino acids',
        subtitle_kk: '18 аминқышқылымен',
        image: 'images/services/pantovye-vanny.jpg',
        desc_ru: 'Уникальная процедура пантолечения с использованием вытяжки из пантов марала.',
        desc_en: 'A unique antler therapy procedure using extract from maral antlers.',
        desc_kk: 'Марал пантысы сығындысын қолданатын бірегей пантотерапия процедурасы.',
        how_ru: 'Курс составляет 10-20 сеансов по 15-20 минут.',
        how_en: 'The course consists of 10-20 sessions of 15-20 minutes.',
        how_kk: 'Курс 10-20 сеанстан тұрады, әрқайсысы 15-20 минут.',
        indications_ru: 'Заболевания опорно-двигательного аппарата, сердечно-сосудистой системы, нервной системы',
        indications_en: 'Musculoskeletal diseases, cardiovascular diseases, nervous system diseases',
        indications_kk: 'Тірек-қимыл аппараты аурулары, жүрек-қан тамырлар жүйесі аурулары, жүйке жүйесі аурулары',
        contraindications_ru: 'Активная форма туберкулеза, злокачественные новообразования, беременность',
        contraindications_en: 'Active form of tuberculosis, malignant neoplasms, pregnancy',
        contraindications_kk: 'Туберкулездің белсенді түрі, қатерлі ісіктер, жүктілік',
        effect_ru: 'Повышение работоспособности, укрепление иммунитета, омоложение организма',
        effect_en: 'Increased performance, strengthening immunity, body rejuvenation',
        effect_kk: 'Қабілеттілікті арттыру, иммунитетті нығайту, денені жасарту'
    },
    2: { 
        title_ru: 'Жаровая ингаляция',
        title_en: 'Heat Inhalation',
        title_kk: 'Ыстық ингаляция',
        subtitle_ru: 'Суховоздушная камера',
        subtitle_en: 'Dry air chamber',
        subtitle_kk: 'Құрғақ ауа камерасы',
        image: 'images/services/ingalyaciya.jpg',
        desc_ru: 'Уникальная процедура с использованием паров отваренных пантов марала.',
        desc_en: 'A unique procedure using steam from boiled maral antlers.',
        desc_kk: 'Қайнатылған марал пантысының буын қолданатын бірегей процедура.',
        how_ru: 'Процедура длится 15-20 минут. Рекомендуется курс из 10-15 процедур.',
        how_en: 'The procedure lasts 15-20 minutes. A course of 10-15 procedures is recommended.',
        how_kk: 'Процедура 15-20 минутқа созылады. 10-15 процедурадан тұратын курс ұсынылады.',
        indications_ru: 'Хронический бронхит, заложенность носа, бронхиальная астма',
        indications_en: 'Chronic bronchitis, nasal congestion, bronchial asthma',
        indications_kk: 'Созылмалы бронхит, мұрынның бітелуі, бронх демікпесі',
        contraindications_ru: 'Острые воспалительные заболевания, онкологические заболевания, беременность',
        contraindications_en: 'Acute inflammatory diseases, oncological diseases, pregnancy',
        contraindications_kk: 'Жедел қабыну аурулары, онкологиялық аурулар, жүктілік',
        effect_ru: 'Очищение дыхательных путей, укрепление иммунитета, снятие стресса',
        effect_en: 'Cleansing of respiratory tract, strengthening immunity, stress relief',
        effect_kk: 'Тыныс жолдарын тазарту, иммунитетті нығайту, стресстен арылу'
    },
    3: { 
        title_ru: 'Пантовые обертывания',
        title_en: 'Antler Wraps',
        title_kk: 'Пантылы орау',
        subtitle_ru: 'Целебная смесь с пантами',
        subtitle_en: 'Healing antler mixture',
        subtitle_kk: 'Пантылы емдік қоспа',
        image: 'images/services/panovye-obertyvania.jpg',
        desc_ru: 'Процедура обертывания тела целебной смесью на основе пантов марала.',
        desc_en: 'Body wrap procedure with a healing mixture based on maral antlers.',
        desc_kk: 'Марал пантысы негізіндегі емдік қоспамен денені орау процедурасы.',
        how_ru: 'На тело наносится целебная смесь, затем тело оборачивается в пленку на 30-40 минут.',
        how_en: 'A healing mixture is applied to the body, then wrapped in film for 30-40 minutes.',
        how_kk: 'Денеге емдік қоспа жағылады, содан кейін дене 30-40 минутқа пленкаға оралады.',
        indications_ru: 'Целлюлит, лишний вес, растяжки, дряблость кожи',
        indications_en: 'Cellulite, excess weight, stretch marks, sagging skin',
        indications_kk: 'Целлюлит, артық салмақ, созылу белгілері, терінің қалжуы',
        contraindications_ru: 'Сердечно-сосудистые заболевания, гипертония, беременность',
        contraindications_en: 'Cardiovascular diseases, hypertension, pregnancy',
        contraindications_kk: 'Жүрек-қан тамыр аурулары, гипертензия, жүктілік',
        effect_ru: 'Выведение токсинов, уменьшение объемов, улучшение состояния кожи',
        effect_en: 'Removal of toxins, reduction of body volume, improvement of skin condition',
        effect_kk: 'Токсиндерді шығару, дене көлемін азайту, тері жағдайын жақсарту'
    },
    4: { 
        title_ru: 'Кумысолечение',
        title_en: 'Kumys Therapy',
        title_kk: 'Қымызбен емдеу',
        subtitle_ru: 'Кобылье молоко',
        subtitle_en: "Mare's milk",
        subtitle_kk: 'Биенің сүті',
        image: 'images/services/kymys.jpg',
        desc_ru: 'Лечение кобыльим молоком и кумысом — кисломолочным напитком.',
        desc_en: "Treatment with mare's milk and kumys — a fermented milk drink.",
        desc_kk: 'Биенің сүтімен және қымызбен емдеу — ашытылған сүт сусыны.',
        how_ru: 'Рекомендуется пить 250 мл саумала 2 раза в день за 30 минут до еды.',
        how_en: 'It is recommended to drink 250 ml of saumal 2 times a day 30 minutes before meals.',
        how_kk: 'Тамақтанудан 30 минут бұрын күніне 2 рет 250 мл саумал ішу ұсынылады.',
        indications_ru: 'Заболевания органов ЖКТ, нарушение обмена веществ, анемия',
        indications_en: 'Gastrointestinal diseases, metabolic disorders, anemia',
        indications_kk: 'Асқазан-ішек аурулары, зат алмасудың бұзылуы, анемия',
        contraindications_ru: 'Непереносимость лактозы, острый гастрит и язва',
        contraindications_en: 'Individual lactose intolerance, acute gastritis and ulcers',
        contraindications_kk: 'Лактозаға жеке көтере алмаушылық, жедел гастрит және ойық жара',
        effect_ru: 'Укрепление иммунитета, нормализация микрофлоры кишечника',
        effect_en: 'Strengthening immunity, normalization of intestinal microflora',
        effect_kk: 'Иммунитетті нығайту, ішек микрофлорасын қалыпқа келтіру'
    },
    5: { 
        title_ru: 'Хиджама',
        title_en: 'Hijama',
        title_kk: 'Хиджама',
        subtitle_ru: 'Баночная терапия',
        subtitle_en: 'Cupping therapy',
        subtitle_kk: 'Банкамен терапия',
        image: 'images/services/hijama.jpg',
        desc_ru: 'Древнейшая процедура кровопускания с помощью вакуумных банок.',
        desc_en: 'The oldest bloodletting procedure using vacuum cups.',
        desc_kk: 'Вакуумды банкаларды қолданатын ежелгі қан алу процедурасы.',
        how_ru: 'На определенные точки тела ставятся банки, создающие вакуум.',
        how_en: 'Cups are placed on certain points of the body, creating a vacuum.',
        how_kk: 'Дененің белгілі бір нүктелеріне вакуум жасайтын банкалар қойылады.',
        indications_ru: 'Головные боли, мигрени, гипертония, бессонница',
        indications_en: 'Headaches, migraines, hypertension, insomnia',
        indications_kk: 'Бас аурулары, мигрень, гипертензия, ұйқысыздық',
        contraindications_ru: 'Артериальная гипотензия, инфекционные заболевания, анемия',
        contraindications_en: 'Arterial hypotension, infectious diseases, anemia',
        contraindications_kk: 'Артериалды гипотензия, жұқпалы аурулар, анемия',
        effect_ru: 'Очищение крови, улучшение кровообращения, повышение иммунитета',
        effect_en: 'Blood cleansing, improved blood circulation, increased immunity',
        effect_kk: 'Қан мен денені тазарту, қан айналымын жақсарту, иммунитетті арттыру'
    },
    6: { 
        title_ru: 'Иглотерапия',
        title_en: 'Acupuncture',
        title_kk: 'Иглотерапия',
        subtitle_ru: 'Иглоукалывание',
        subtitle_en: 'Acupuncture',
        subtitle_kk: 'Инелік ем',
        image: 'images/services/igloterapiya.jpg',
        desc_ru: 'Иглоукалывание по биологически активным точкам.',
        desc_en: 'Acupuncture on biologically active points.',
        desc_kk: 'Биологиялық белсенді нүктелер бойынша инемен емдеу.',
        how_ru: 'Тонкие стерильные иглы вводятся в определенные точки на теле.',
        how_en: 'Thin sterile needles are inserted into specific points on the body.',
        how_kk: 'Жіңішке стерильді инемен дененің белгілі бір нүктелеріне енгізіледі.',
        indications_ru: 'Остеохондроз, артриты, боли в спине, невралгии',
        indications_en: 'Osteochondrosis, arthritis, back pain, neuralgia',
        indications_kk: 'Остеохондроз, артриттер, арқа ауруы, невралгия',
        contraindications_ru: 'Детский возраст до 1 года, онкологические заболевания',
        contraindications_en: 'Children under 1 year of age, oncological diseases',
        contraindications_kk: '1 жасқа дейінгі балалар, онкологиялық аурулар',
        effect_ru: 'Снятие болевого синдрома, нормализация обмена веществ',
        effect_en: 'Pain relief, normalization of metabolism',
        effect_kk: 'Ауырсыну синдромын басу, зат алмасуды қалыпқа келтіру'
    },
    7: { 
        title_ru: 'Пантовые маски',
        title_en: 'Antler Masks',
        title_kk: 'Пантылы маскалар',
        subtitle_ru: 'Для лица и тела',
        subtitle_en: 'For face and body',
        subtitle_kk: 'Бет және денеге',
        image: 'images/services/pantovye-maski.jpg',
        desc_ru: 'Маски для лица и тела из живой крови пант марала.',
        desc_en: 'Face and body masks from live maral antler blood.',
        desc_kk: 'Тірі марал пантысы қанынан жасалған бет және дене маскалары.',
        how_ru: 'На лицо/тело наносится маска из пантогематогена на 20-30 минут.',
        how_en: 'A mask of panthematogen is applied to the face/body for 20-30 minutes.',
        how_kk: 'Бетке/денеге пантогематогеннен жасалған маска 20-30 минутқа жағылады.',
        indications_ru: 'Старение кожи, морщины, акне, высыпания',
        indications_en: 'Skin aging, wrinkles, acne, rashes',
        indications_kk: 'Терінің қартаюы, әжімдер, безеу, бөртпелер',
        contraindications_ru: 'Индивидуальная непереносимость, открытые раны',
        contraindications_en: 'Individual intolerance, open wounds',
        contraindications_kk: 'Жеке көтере алмаушылық, ашық жаралар',
        effect_ru: 'Омоложение кожи, разглаживание морщин',
        effect_en: 'Skin rejuvenation, wrinkle smoothing',
        effect_kk: 'Теріні жасарту, әжімдерді тегістеу'
    },
    8: { 
        title_ru: 'Скрабы для тела',
        title_en: 'Body Scrubs',
        title_kk: 'Дене скрабтары',
        subtitle_ru: 'Кофейные и медовые',
        subtitle_en: 'Coffee and honey',
        subtitle_kk: 'Кофе және бал',
        image: 'images/services/skraby.jpg',
        desc_ru: 'Кофейные и медовые скрабы с морской солью и эфирными маслами.',
        desc_en: 'Coffee and honey scrubs with sea salt and essential oils.',
        desc_kk: 'Теңіз тұзы мен эфир майлары қосылған кофе және бал скрабтары.',
        how_ru: 'Нанесение скраба на тело массажными движениями, затем смывание.',
        how_en: 'Apply the scrub to the body with massaging movements, then rinse.',
        how_kk: 'Скрабты денеге массаж қимылдарымен жағыңыз, содан кейін шайыңыз.',
        indications_ru: 'Целлюлит, тусклая кожа, нарушение кровообращения',
        indications_en: 'Cellulite, dull skin, poor circulation',
        indications_kk: 'Целлюлит, күңгірт тері, қан айналымының бұзылуы',
        contraindications_ru: 'Открытые раны, кожные заболевания в острой фазе',
        contraindications_en: 'Open wounds, skin diseases in the acute phase',
        contraindications_kk: 'Ашық жаралар, жедел фазадағы тері аурулары',
        effect_ru: 'Очищение кожи, выведение токсинов, улучшение кровообращения',
        effect_en: 'Skin cleansing, removal of toxins, improved blood circulation',
        effect_kk: 'Теріні тазарту, токсиндерді шығару, қан айналымын жақсарту'
    },
    9: { 
        title_ru: 'Массаж',
        title_en: 'Massage',
        title_kk: 'Массаж',
        subtitle_ru: 'Лечебный и расслабляющий',
        subtitle_en: 'Therapeutic and relaxing',
        subtitle_kk: 'Емдік және релаксациялық',
        image: 'images/services/massazh.jpg',
        desc_ru: 'Профессиональный массаж по зонам тела с использованием целебных масел.',
        desc_en: 'Professional massage of body areas using healing oils.',
        desc_kk: 'Емдік майларды қолдана отырып, дене аймақтарын кәсіби массаж.',
        how_ru: 'Массажист прорабатывает проблемные зоны тела. Длительность 30-60 минут.',
        how_en: 'The massage therapist works on problem areas of the body. Duration 30-60 minutes.',
        how_kk: 'Массажист майларды пайдаланып, дененің проблемалы аймақтарын өңдейді. Ұзақтығы 30-60 минут.',
        indications_ru: 'Боли в спине и суставах, мышечное напряжение, остеохондроз',
        indications_en: 'Back and joint pain, muscle tension, osteochondrosis',
        indications_kk: 'Арқа және буын ауруы, бұлшықет кернеуі, остеохондроз',
        contraindications_ru: 'Острые воспалительные заболевания, онкология, высокая температура',
        contraindications_en: 'Acute inflammatory diseases, oncology, high fever',
        contraindications_kk: 'Жедел қабыну аурулары, онкология, жоғары температура',
        effect_ru: 'Снятие мышечного напряжения, улучшение кровообращения',
        effect_en: 'Relief of muscle tension, improved blood circulation',
        effect_kk: 'Бұлшықет кернеуін басу, қан айналымын жақсарту'
    },
    10: { 
        title_ru: 'Фитобар',
        title_en: 'Herbal Bar',
        title_kk: 'Фито-бар',
        subtitle_ru: 'Целебные травяные чаи',
        subtitle_en: 'Healing herbal teas',
        subtitle_kk: 'Емдік шөп шайлары',
        image: 'images/services/fitobar.jpg',
        desc_ru: 'Целебные фиточаи из алтайских трав: бадан, зверобой, копеечник.',
        desc_en: 'Healing herbal teas from Altai herbs: bergenia, St. John\'s wort, hedysarum.',
        desc_kk: 'Алтай шөптерінен емдік фитошайлар: бадан, ақтамыр, жантақ.',
        how_ru: 'Подаются теплые фиточаи из алтайских лекарственных трав.',
        how_en: 'Warm herbal teas from Altai medicinal herbs are served.',
        how_kk: 'Алтай емдік шөптерінен жасалған жылы шөп шайлары беріледі.',
        indications_ru: 'Ослабленный иммунитет, простудные заболевания, нарушение пищеварения',
        indications_en: 'Weakened immunity, colds, digestive disorders',
        indications_kk: 'Иммунитеттің әлсіреуі, суық тию, ас қорытудың бұзылуы',
        contraindications_ru: 'Индивидуальная непереносимость трав, беременность',
        contraindications_en: 'Individual intolerance to herbs, pregnancy',
        contraindications_kk: 'Шөптерге жеке көтере алмаушылық, жүктілік',
        effect_ru: 'Укрепление иммунитета, очищение организма, снятие стресса',
        effect_en: 'Strengthening immunity, body cleansing, stress relief',
        effect_kk: 'Иммунитетті нығайту, денені тазарту, стресстен арылу'
    },
    11: { 
        title_ru: 'Терренкур',
        title_en: 'Terrenkur',
        title_kk: 'Терренкур',
        subtitle_ru: 'Лечебная ходьба',
        subtitle_en: 'Therapeutic walking',
        subtitle_kk: 'Емдік серуен',
        image: 'images/services/terrenkyr.jpg',
        desc_ru: 'Лечебная ходьба по горным тропам Катон-Карагая.',
        desc_en: 'Therapeutic walking along the mountain trails of Katon-Karagay.',
        desc_kk: 'Катон-Қарағайдың тау жолдарымен емдік серуендеу.',
        how_ru: 'Прогулки по специальным маршрутам в горах.',
        how_en: 'Walks along special routes in the mountains.',
        how_kk: 'Таулардағы арнайы маршруттар бойынша серуендеу.',
        indications_ru: 'Сердечно-сосудистые заболевания, нарушение обмена веществ, стресс',
        indications_en: 'Cardiovascular diseases, metabolic disorders, stress',
        indications_kk: 'Жүрек-қан тамыр аурулары, зат алмасудың бұзылуы, стресс',
        contraindications_ru: 'Серьезные сердечные заболевания, острые заболевания',
        contraindications_en: 'Serious heart disease, acute diseases',
        contraindications_kk: 'Ауыр жүрек аурулары, жедел аурулар',
        effect_ru: 'Укрепление сердечно-сосудистой системы, повышение выносливости',
        effect_en: 'Strengthening the cardiovascular system, increasing endurance',
        effect_kk: 'Жүрек-қан тамырлар жүйесін нығайту, төзімділікті арттыру'
    },
    12: { 
        title_ru: 'Конные прогулки',
        title_en: 'Horse Riding',
        title_kk: 'Атпен серуендеу',
        subtitle_ru: 'По горам Катон-Карагая',
        subtitle_en: 'Through the mountains of Katon-Karagay',
        subtitle_kk: 'Катон-Қарағай таулары арқылы',
        image: 'images/services/horse.jpg',
        desc_ru: 'Прогулки на лошадях по живописным местам Катон-Карагайского национального парка.',
        desc_en: 'Horseback riding through the picturesque places of Katon-Karagay National Park.',
        desc_kk: 'Катон-Қарағай ұлттық паркінің көркем жерлері арқылы атпен серуендеу.',
        how_ru: 'Конные прогулки с инструктором по окрестностям базы.',
        how_en: 'Horseback riding with an instructor around the base.',
        how_kk: 'База маңында нұсқаушымен атпен серуендеу.',
        indications_ru: 'Стресс, депрессия, желание активного отдыха',
        indications_en: 'Stress, depression, desire for active recreation',
        indications_kk: 'Стресс, депрессия, белсенді демалысқа деген ұмтылыс',
        contraindications_ru: 'Серьезные травмы позвоночника, острые заболевания, беременность',
        contraindications_en: 'Serious spinal injuries, acute diseases, pregnancy',
        contraindications_kk: 'Омыртқаның ауыр жарақаттары, жедел аурулар, жүктілік',
        effect_ru: 'Заряд позитива, общение с лошадьми, активный отдых',
        effect_en: 'Positive charge, communication with horses, active recreation',
        effect_kk: 'Позитивті заряд, жылқылармен қарым-қатынас, белсенді демалыс'
    },
    13: { 
        title_ru: 'Саумал',
        title_en: 'Saumal',
        title_kk: 'Саумал',
        subtitle_ru: 'Кобылье молоко',
        subtitle_en: "Mare's milk",
        subtitle_kk: 'Биенің сүті',
        image: 'images/services/saumal.jpg',
        desc_ru: 'Свежее парное кобылье молоко.',
        desc_en: "Fresh steamed mare's milk.",
        desc_kk: 'Жаңа піскен бие сүті.',
        how_ru: 'Пьется в свежем виде (обязательно в первые 3 часа после дойки).',
        how_en: 'Drunk fresh (must be within the first 3 hours after milking).',
        how_kk: 'Жаңа піскен күйінде ішеді (сауылғаннан кейінгі алғашқы 3 сағат ішінде).',
        indications_ru: 'Детское питание, ослабленный иммунитет, заболевания ЖКТ',
        indications_en: 'Baby food, weakened immunity, gastrointestinal diseases',
        indications_kk: 'Балалар тағамы, иммунитеттің әлсіреуі, асқазан-ішек аурулары',
        contraindications_ru: 'Непереносимость лактозы, аллергия на молочный белок',
        contraindications_en: 'Lactose intolerance, allergy to milk protein',
        contraindications_kk: 'Лактозаны көтере алмау, сүт ақуызына аллергия',
        effect_ru: 'Укрепление иммунитета, легкое усвоение, питательность',
        effect_en: 'Strengthening immunity, easy digestibility, nutrition',
        effect_kk: 'Иммунитетті нығайту, оңай сіңу, қоректілік'
    }
};